# NUMPY ASSIGNMENT 03

In [1]:
import numpy as np

# TASK 1
--------------------------CREATING RANDOM ARRAY OF 10 INTEGERS BETWEEN 0 - 100--------------------------

In [2]:
ran_arr = np.random.randint(1, 100, size=(10))
ran_arr

array([ 7, 42, 41, 29, 34, 24, 18, 72, 12, 43])

--------------------------RESHAPE 1D ARRAY INTO 2D ARRAY--------------------------

In [3]:
ran_arr.reshape(2,5)

array([[ 7, 42, 41, 29, 34],
       [24, 18, 72, 12, 43]])

# TASK 2
--------------------------ELEMENT WISE MATHEMATICAL OPERATIONS--------------------------

In [4]:
arr1 = np.random.randint(1,10,size=(5))
arr2 = np.random.randint(11,20 ,size=(5))
arr1, arr2

(array([3, 3, 8, 1, 9]), array([17, 18, 12, 18, 17]))

In [5]:
add = np.add(arr1 , arr2)
sub = np.subtract(arr1 , arr2)
mul = np.multiply(arr1 , arr2)
div = np.divide(arr1 , arr2)
add, sub, mul, div

(array([20, 21, 20, 19, 26]),
 array([-14, -15,  -4, -17,  -8]),
 array([ 51,  54,  96,  18, 153]),
 array([0.17647059, 0.16666667, 0.66666667, 0.05555556, 0.52941176]))


--------------------------MEAN, MEDIAN, STANDARD DEVIATION & VARIANCE OF NUMPY ARRAY--------------------------

In [6]:
num_arr = [31,56,98,45,67]

Mean = np.mean(num_arr)
Median = np.median(num_arr)
SD = np.std(num_arr)
SD_rounded = round(SD, 2)
Variance = np.var(num_arr)
variance_rounded = round(Variance, 2)

Mean , Median , SD_rounded , variance_rounded

(59.4, 56.0, 22.69, 514.64)

# TASK 3
--------------------SUBARRAY FROM 2D--------------------

In [7]:
arr_2d = np.random.randint(1,10,size=(5,5))
arr_2d

array([[9, 9, 2, 1, 6],
       [6, 2, 3, 9, 5],
       [2, 8, 7, 3, 7],
       [8, 9, 1, 3, 1],
       [5, 5, 5, 9, 7]])

In [8]:
extract_subarr = arr_2d[1:4, 2:4]
extract_subarr

array([[3, 9],
       [7, 3],
       [1, 3]])

--------------------SPECIFIC ROW AND COLUMN--------------------

In [9]:
row = arr_2d[:1]
row

array([[9, 9, 2, 1, 6]])

In [10]:
col = arr_2d[:5, 1:2]
col

array([[9],
       [2],
       [8],
       [9],
       [5]])

# TASK 4
------------------------------------ADVANCED OPERTAIONS----------------------------------

In [11]:
op2d = np.array([[3,6,9],[2,5,6],[7,1,3,]])
op2d1 = np.array([[1,2,3],[2,3,4],[5,6,7]])
mat = np.dot(op2d,op2d1)
mat

array([[60, 78, 96],
       [42, 55, 68],
       [24, 35, 46]])

------------------------DOT PRODUCT--------------------------------------

In [12]:
vector1 = np.array([9,8,7])
vector2 = np.array([3,2,1])
dot_product = np.dot(vector1, vector2)
dot_product

50

---------------SYSTEM OF EQUATION-------------------------

In [13]:
A = np.array([[1,2,3],[4,-5,6],[7,8,9]])
b = np.array([9,7,6])

solution = np.linalg.solve(A, b)
solution

array([-5.275,  0.05 ,  4.725])

# TASK 5
--------------------APPLYING FUNCTION--------------------------

In [14]:
z = np.array([[1,2,3],[4,5,6],[7,8,9]])

def condi(value):
    if value%2 == 0:
        value = "Even"
    else: 
        value = "Odd"
    return value

vectorize_function = np.vectorize(condi)
result = vectorize_function(z)
result

array([['Odd', 'Even', 'Odd'],
       ['Even', 'Odd', 'Even'],
       ['Odd', 'Even', 'Odd']], dtype='<U4')

--------------COMPUTATION ON ARRAY-----------------------

In [15]:
array = np.array([1, 2, 3, 4, 5])

def computation(array):
    result_add = array + 2
    result_sub = array - 1
    result_mul = array * 3 
    result_div = array / 2
    result_combined = (array + 2) * 3

    return result_add, result_sub, result_mul, result_div, result_combined


vector = np.vectorize(computation)
results = vector(array)
results


(array([3, 4, 5, 6, 7]),
 array([0, 1, 2, 3, 4]),
 array([ 3,  6,  9, 12, 15]),
 array([0.5, 1. , 1.5, 2. , 2.5]),
 array([ 9, 12, 15, 18, 21]))